Home/Home/urls.py
from django.contrib import admin
from django.urls import path, include
from home_auth import views as auth_views  # added
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("school.urls")),
    path('student/', include(("student.urls", "student"), namespace="student")),
    path('authentication/', include('home_auth.urls')),
    path('forgot-password/', auth_views.forgot_password_view),  # new root-level mapping
    path('reset_password/<str:token>/', auth_views.reset_password_view),  # new root-level mapping
    
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/student/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'student'
urlpatterns = [
    path('', views.student_list, name='student_list'),
    path('add/', views.add_student, name='add_student'),
    path('students/<str:slug>/', views.view_student, name='view_student'),
    path('edit/<str:slug>/', views.edit_student, name='edit_student'),
    path('delete/<str:slug>/', views.delete_student, name='delete_student'),
]

Home/student/models.py
from django.db import models
from django.utils.text import slugify
from django.core.exceptions import ValidationError

# Create your models here.
class Parent(models.Model):
    father_name = models.CharField(max_length=100)
    father_occupation = models.CharField(max_length=100, blank=True)
    father_mobile = models.CharField(max_length=15)
    father_email = models.EmailField(max_length=100)
    mother_name = models.CharField(max_length=100)
    mother_occupation = models.CharField(max_length=100, blank=True)
    mother_mobile = models.CharField(max_length=15)
    mother_email = models.EmailField(max_length=100)
    present_address = models.TextField()
    permanent_address = models.TextField()

    def __str__(self):
        return f"{self.father_name} & {self.mother_name}"

class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    student_id = models.CharField(max_length=20)
    gender = models.CharField(max_length=10, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')])
    date_of_birth = models.DateField()
    student_class = models.CharField(max_length=50)
    religion = models.CharField(max_length=50)
    joining_date = models.DateField()
    mobile_number = models.CharField(max_length=15)
    admission_number = models.CharField(max_length=20)
    section = models.CharField(max_length=10)
    student_image = models.ImageField(upload_to='students/', blank=True)
    parent = models.OneToOneField(Parent, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=255, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(f"{self.first_name}-{self.last_name}-{self.student_id}")
            slug = base_slug
            counter = 1
            # Check if slug already exists and modify it if needed
            while Student.objects.filter(slug=slug).exclude(pk=self.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super(Student, self).save(*args, **kwargs)
    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.student_id})"
  

Home/student/views.py
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import render ,  get_object_or_404
from .models import Parent as Parent, Student as Student, models as models, slugify as slugify
from django.contrib import messages
from school.models import Notification


# Create your views here.

def create_notification(user, message):
    """Create a notification for the user"""
    Notification.objects.create(user=user, message=message)


def add_student(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        student_id = request.POST.get('student_id')
        gender = request.POST.get('gender')
        date_of_birth = request.POST.get('date_of_birth')
        student_class = request.POST.get('student_class')
        religion = request.POST.get('religion')
        joining_date = request.POST.get('joining_date')
        mobile_number = request.POST.get('mobile_number')
        admission_number = request.POST.get('admission_number')
        section = request.POST.get('section')
        student_image = request.FILES.get('student_image')

        # Retrieve parent data from the form
        father_name = request.POST.get('father_name')
        father_occupation = request.POST.get('father_occupation')
        father_mobile = request.POST.get('father_mobile')
        father_email = request.POST.get('father_email')
        mother_name = request.POST.get('mother_name')
        mother_occupation = request.POST.get('mother_occupation')
        mother_mobile = request.POST.get('mother_mobile')
        mother_email = request.POST.get('mother_email')
        present_address = request.POST.get('present_address')
        permanent_address = request.POST.get('permanent_address')

        # save parent information
        parent = Parent.objects.create(
            father_name= father_name,
            father_occupation= father_occupation,
            father_mobile= father_mobile,
            father_email= father_email,
            mother_name= mother_name,
            mother_occupation= mother_occupation,
            mother_mobile= mother_mobile,
            mother_email= mother_email,
            present_address= present_address,
            permanent_address= permanent_address
        )

        # Save student information
        student = Student.objects.create(
            first_name= first_name,
            last_name= last_name,
            student_id= student_id,
            gender= gender,
            date_of_birth= date_of_birth,
            student_class= student_class,
            religion= religion,
            joining_date= joining_date,
            mobile_number = mobile_number,
            admission_number = admission_number,
            section = section,
            student_image = student_image,
            parent = parent
         )
        create_notification(request.user, f"Added student: {student.first_name} {student.last_name}")
        messages.success(request, "Student added Successfully")
        # return render(request, "student_list")

  

    
    return render(request, "students/add-student.html")

def student_list(request):

    student_list = Student.objects.select_related('parent').all()
    unread_notifications = request.user.notification_set.filter(is_read=False)
    unread_notification_count = unread_notifications.count()
    context = {
        'student_list': student_list,
        'unread_notification': unread_notifications,
        'unread_notification_count': unread_notification_count
    }

  


    return render(request, "students/students.html", context)

def edit_student(request, slug):
    
    student =  get_object_or_404(Student, slug=slug)
    parent = student.parent if hasattr(student, 'parent') else None
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        student_id = request.POST.get('student_id')
        gender = request.POST.get('gender')
        date_of_birth = request.POST.get('date_of_birth')
        student_class = request.POST.get('student_class')
        religion = request.POST.get('religion')
        joining_date = request.POST.get('joining_date')
        mobile_number = request.POST.get('mobile_number')
        admission_number = request.POST.get('admission_number')
        section = request.POST.get('section')
        student_image = request.FILES.get('student_image')

        # Retrieve parent data from the form
        parent.father_name = request.POST.get('father_name')
        parent.father_occupation = request.POST.get('father_occupation')
        parent.father_mobile = request.POST.get('father_mobile')
        parent.father_email = request.POST.get('father_email')
        parent.mother_name = request.POST.get('mother_name')
        parent.mother_occupation = request.POST.get('mother_occupation')
        parent.mother_mobile = request.POST.get('mother_mobile')
        parent.mother_email = request.POST.get('mother_email')
        parent.present_address = request.POST.get('present_address')
        parent.permanent_address = request.POST.get('permanent_address')
        parent.save()
        
        
       

        # Save student information
        
        student.first_name= first_name
        student.last_name= last_name
        student.student_id= student_id
        student.gender= gender
        student.date_of_birth= date_of_birth
        student.student_class= student_class
        student.religion= religion
        student.joining_date= joining_date
        student.mobile_number = mobile_number
        student.admission_number = admission_number
        student.section = section
        student.student_image = student_image
        student.parent = parent
        student.save()
    create_notification(request.user, f"Updated student: {student.first_name} {student.last_name}")
     
    return render(request, "students/students.html")
    return render(request, "students/edit-student.html", {'student': student, 'parent': parent}) 
                 

def view_student(request, slug):
    student =  get_object_or_404(Student, slug=slug)
    context = {
        'student': student
    }
    return render(request, "students/student-details.html", context)

def delete_student(request, slug):
    if request.method == "POST":
        student = get_object_or_404(Student, slug=slug)
        student_name = f"{student.first_name} {student.last_name}"
        student.delete()
        create_notification(request.user, f"Deleted student: {student_name}")

        return render(request, "students/students.html")
    return HttpResponseForbidden()

Home/templates/students/add-student.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
   
         <div class="page-wrapper">
            <div class="content container-fluid">
               <div class="page-header">
                  <div class="row align-items-center">
                     <div class="col">
                        <h3 class="page-title">Add Students</h3>
                        <ul class="breadcrumb">
                           <li class="breadcrumb-item"><a href="{% url 'student:student_list' %}">Students</a></li>
                           <li class="breadcrumb-item active">Add Students</li>
                        </ul>
                     </div>
                  </div>
               </div>
               <div class="row">
                  <div class="col-sm-12">
                     <div class="card">
                        <div class="card-body">
                           <form method="POST"   enctype="multipart/form-data">
                              {% csrf_token %}
                              <div class="row">
                                 <div class="col-12">
                                    <h5 class="form-title"><span>Student Information</span></h5>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>First Name</label>
                                       <input type="text" class="form-control" name="first_name" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Last Name</label>
                                       <input type="text" class="form-control" name = "last_name" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Student Id</label>
                                       <input type="text" class="form-control" name = "student_id" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Gender</label>
                                       <select class="form-control" name="gender" required>
                                          <option value="">Select Gender</option>
                                          <option value="Female">Female</option>
                                          <option value="Male">Male</option>
                                          <option value="Others">Others</option>
                                       </select>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Date of Birth</label>
                                       <div>
                                          <input type="date" class="form-control" name="date_of_birth" required>
                                       </div>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Class</label>
                                       <input type="text" class="form-control" name="student_class" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Religion</label>
                                       <input type="text" class="form-control" name="religion" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Joining Date</label>
                                       <div>
                                          <input type="date" class="form-control" name="joining_date" required>
                                       </div>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Mobile Number</label>
                                       <input type="text" class="form-control" name="mobile_number" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Admission Number</label>
                                       <input type="text" class="form-control" name="admission_number" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Section</label>
                                       <input type="text" class="form-control" name="section" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Student Image</label>
                                       <input type="file" class="form-control" name="student_image">
                                    </div>
                                 </div>
                                 <div class="col-12">
                                    <h5 class="form-title"><span>Parent Information</span></h5>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Father's Name</label>
                                       <input type="text" class="form-control" name="father_name" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Father's Occupation</label>
                                       <input type="text" class="form-control" name="father_occupation" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Father's Mobile</label>
                                       <input type="text" class="form-control" name="father_mobile" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Father's Email</label>
                                       <input type="email" class="form-control" name="father_email" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Mother's Name</label>
                                       <input type="text" class="form-control" name="mother_name" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Mother's Occupation</label>
                                       <input type="text" class="form-control" name="mother_occupation" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                     <div class="form-group">
                                       <label>Mother's Mobile</label>
                                       <input type="text" class="form-control" name="mother_mobile" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Mother's Email</label>
                                       <input type="email" class="form-control" name="mother_email" required>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Present Address</label>
                                       <textarea class="form-control" name="present_address" required></textarea>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Permanent Address</label>
                                       <textarea class="form-control" name="permanent_address" required></textarea>
                                    </div>
                                 </div>
                                 <div class="col-12">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                 </div>
                              </div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <script src="{%static 'assets/js/jquery-3.6.0.min.js' %}"></script>
      <script src="{%static 'assets/js/popper.min.js' %}"></script>
      <script src="{%static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
      <script src="{%static 'assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
      <script src="{%static 'assets/js/script.js' %}"></script>
   </body>
   <!-- Mirrored from preschool.dreamguystech.com/html-template/add-student.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Oct 2021 11:11:50 GMT -->
</html>
{% endblock %}

Home/templates/students/students.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
   
         <div class="page-wrapper">
            <div class="content container-fluid">
               <div class="page-header">
                  <div class="row align-items-center">
                     <div class="col">
                        <h3 class="page-title">Students</h3>
                        <ul class="breadcrumb">
                           <li class="breadcrumb-item"><a href="{% url 'student_dashboard' %}">Dashboard</a></li>
                           <li class="breadcrumb-item active">Students</li>
                        </ul>
                     </div>
                     <div class="col-auto text-right float-right ml-auto">
                        <a href="#" class="btn btn-outline-primary mr-2"><i class="fas fa-download"></i> Download</a>
                        <a href="{% url 'student:add_student' %}" class="btn btn-primary"><i class="fas fa-plus"></i></a>
                     </div>
                  </div>
               </div>
               <div class="row">
                  <div class="col-sm-12">
                     <div class="card card-table">
                        <div class="card-body">
                           <div class="table-responsive">
                              <table class="table table-hover table-center mb-0 datatable">
                                 <thead>
                                    <tr>
                                       <th>ID</th>
                                       <th>Name</th>
                                       <th>Class</th>
                                       <th>DOB</th>
                                       <th>Parent Name</th>
                                       <th>Mobile Number</th>
                                       <th>Address</th>
                                       <th class="text-right">Action</th>
                                    </tr>
                                 </thead>
                                 <tbody>
                                    {% for student in student_list %}
                                    <tr>
                                       <td>{{ student.student_id}}</td>
                                       <td>
                                          <h2 class="table-avatar">
                                             <a href="{% url 'student:view_student' student.slug %}" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="{% if student.student_image %}{{ student.student_image.url }}{% else %}https://via.placeholder.com/40{% endif %}" alt="{user.image}"></a>
                                             <a href="{% url 'student:view_student' student.slug %}">{{ student.first_name }} {{ student.last_name}}</a>
                                          </h2>
                                       </td>
                                       <td>{{ student.student_class }}</td>
                                       <td>{{ student.date_of_birth|date:"d M Y" }}</td>
                                       <td>{{ student.parent.father_name }} / {{ student.parent.mother_name }}</td>
                                       <td>{{ student.mobile_number }}</td>
                                       <td>{{ student.parent.present_address }}</td>
                                       <td class="text-right">
                                          <div class="actions">
                                             <a href="{% url 'student:edit_student' student.slug %}" class="btn btn-sm bg-success-light mr-2">
                                                 <i class="fas fa-pen"></i>
                                             </a>
                                             <form action="{% url 'student:delete_student' student.slug %}" method="POST" style="display:inline;">
                                                 {% csrf_token %}
                                                 <button type="submit" class="btn btn-sm bg-danger-light" onclick="return confirm('Are you sure you want to delete this student?');">
                                                     <i class="fas fa-trash"></i>
                                                 </button>
                                             </form>
                                         </div>
                                       </td>
                                    </tr>
                                    {% endfor %}
                                 </tbody>
                              </table>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <footer>
               <p><center>Copyright © 2020 Dreamguys.</center></p>
            </footer>
         </div>
      </div>
      <script src="{%static 'assets/js/jquery-3.6.0.min.js' %}"></script>
      <script src="{%static 'assets/js/popper.min.js' %}"></script>
      <script src="{%static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
      <script src="{%static 'assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
      <script src="{%static 'assets/plugins/datatables/datatables.min.js' %}"></script>
      <script src="{%static 'assets/js/script.js' %}"></script>
   </body>
   <!-- Mirrored from preschool.dreamguystech.com/html-template/students.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Oct 2021 11:11:49 GMT -->
</html>


{% endblock %}